# Generated by Django 6.0.3 on 2026-03-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_order_date_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='is_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='offer_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='offer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
