# Generated by Django 6.0.3 on 2026-03-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_food_discount_food_is_offer_food_offer_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='stock',
            field=models.IntegerField(default=10),
        ),
    ]
